Repository Sylius/SyliusResourceBundle, pull requests merged in 2020-04, with the labels that each got.

#151 [Maintenance] Bump ApiTestCase to v5.0
  composer.json
  src/Bundle/test/src/Tests/Responses/books/create_response.json
  src/Bundle/test/src/Tests/Responses/books/index_response.json
  src/Bundle/test/src/Tests/Responses/books/paginated_index_response.json
  src/Bundle/test/src/Tests/Responses/books/show_response.json
  src/Bundle/test/src/Tests/Responses/comic-books/create_response.json
  src/Bundle/test/src/Tests/Responses/comic-books/index_response.json
  src/Bundle/test/src/Tests/Responses/comic-books/show_response.json
  src/Bundle/test/src/Tests/Responses/comic-books/versioned_create_response.json
  src/Bundle/test/src/Tests/Responses/comic-books/versioned_index_response.json
  src/Bundle/test/src/Tests/Responses/comic-books/versioned_show_response.json
  src/Bundle/test/src/Tests/Responses/gedmos/create_response.json
Labels: Maintenance

#159 Remove duplicated docblocks
  src/Bundle/test/app/AppKernel.php
  src/Bundle/test/src/AppBundle/AppBundle.php
  src/Bundle/test/src/AppBundle/Entity/Book.php
  src/Bundle/test/src/AppBundle/Entity/BookTranslation.php
  src/Bundle/test/src/AppBundle/Entity/ComicBook.php
  src/Bundle/test/src/AppBundle/Form/Type/BookTranslationType.php
  src/Bundle/test/src/AppBundle/Form/Type/BookType.php
  src/Bundle/test/src/Tests/Controller/BookApiTest.php
  src/Bundle/test/src/Tests/Controller/ComicBookApiTest.php
  src/Bundle/test/src/Tests/Controller/GedmoApiTest.php
Labels: Maintenance

#161 [HOTFIX] Conflict with amphp/amp 2.4.3
  composer.json
Labels: Bug

#160 ResourceBundle documentation extracted to its repository
  README.md
  docs/configuration.md
  docs/create_resource.md
  docs/delete_resource.md
  docs/forms.md
  docs/index.md
  docs/index_resources.md
  docs/installation.md
  docs/reference.md
  docs/routing.md
  docs/services.md
  docs/show_resource.md
  docs/update_resource.md
Labels: Maintenance

#162 [Documentation] Fix index menu
  docs/index.md
Labels: Bug, Maintenance
