Repository Sylius/SyliusResourceBundle, pull requests merged in 2021-12, with the labels that each got.

#342 Fix CI
  .github/workflows/build.yml
  composer.json
  phpstan.neon
  psalm.xml
  src/Bundle/Controller/Parameters.php
  src/Bundle/Storage/CookieStorage.php
  src/Component/composer.json
Labels: Bug

#340 Allow jms/serializer-bundle 4
  composer.json
Labels: Maintenance

#343 Change ECS config to php and run it
  easy-coding-standard.yml
  ecs.php
  src/Bundle/AbstractResourceBundle.php
  src/Bundle/Command/DebugResourceCommand.php
  src/Bundle/Controller/ResourceController.php
  src/Bundle/DependencyInjection/Compiler/RegisterStateMachinePass.php
  src/Bundle/Doctrine/ODM/MongoDB/DocumentRepository.php
  src/Bundle/Doctrine/ODM/PHPCR/DocumentRepository.php
  src/Bundle/Doctrine/ODM/PHPCR/EventListener/DefaultParentListener.php
  src/Bundle/Doctrine/ODM/PHPCR/EventListener/NameResolverListener.php
  src/Bundle/EventListener/ORMTranslatableListener.php
  src/Bundle/Tests/DependencyInjection/Compiler/RegisterFormBuilderPassTest.php
  src/Bundle/spec/Controller/FlashHelperSpec.php
  src/Bundle/spec/DependencyInjection/Compiler/Helper/TargetEntitiesResolverSpec.php
  src/Bundle/spec/Doctrine/ODM/PHPCR/EventListener/NameResolverListenerSpec.php
  src/Bundle/spec/Grid/Parser/OptionsParserSpec.php
  src/Bundle/test/config/bundles.php
  src/Bundle/test/src/Entity/Author.php
  src/Bundle/test/src/Entity/Book.php
  src/Bundle/test/src/Entity/ComicBook.php
Labels: Enhancement, Maintenance, DX

#330 Add a simple way to use the new service entity repository
  docs/configuration.md
  src/Bundle/Doctrine/ORM/EntityRepository.php
  src/Bundle/Doctrine/ORM/ResourceRepositoryTrait.php
  src/Bundle/Tests/Resource/ResourceServicesTest.php
  src/Bundle/test/config/doctrine/ComicBook.orm.yml
  src/Bundle/test/config/services.yaml
  src/Bundle/test/src/Repository/ComicBookRepository.php
Labels: Feature

#332 Change all MasterRequest calls to MainRequest
  src/Bundle/Storage/CookieStorage.php
Labels: Enhancement, DX
