Repository Sylius/SyliusResourceBundle, pull requests merged in 2022-10, with the labels that each got.

#467 [README] Add development section and update links
  README.md
Labels: Maintenance

#478 Add tests with grids
  .github/workflows/build.yml
  composer.json
  src/Bundle/test/config/bundles.php
  src/Bundle/test/config/packages/test/grids.yaml
  src/Bundle/test/config/routes.yaml
  src/Bundle/test/src/Tests/Controller/ScienceBookUiTest.php
  src/Bundle/test/templates/ScienceBook/index.html.twig
Labels: Enhancement, DX

#450 Adjust when some runtime deprecation notices are triggered and use Symfony's `trigger_deprecation()` helper
  composer.json
  src/Bundle/AbstractResourceBundle.php
  src/Bundle/Controller/ControllerTrait.php
  src/Bundle/Controller/FlashHelper.php
  src/Bundle/DependencyInjection/Compiler/Helper/TargetEntitiesResolver.php
  src/Bundle/DependencyInjection/Compiler/PagerfantaBridgePass.php
  src/Bundle/DependencyInjection/Driver/Doctrine/DoctrineODMDriver.php
  src/Bundle/DependencyInjection/Driver/Doctrine/DoctrinePHPCRDriver.php
  src/Bundle/DependencyInjection/PagerfantaConfiguration.php
  src/Bundle/DependencyInjection/PagerfantaExtension.php
  src/Bundle/DependencyInjection/SyliusResourceExtension.php
  src/Bundle/Doctrine/ODM/MongoDB/DocumentRepository.php
  src/Bundle/Doctrine/ODM/MongoDB/TranslatableRepository.php
  src/Bundle/Doctrine/ODM/PHPCR/DocumentRepository.php
  src/Bundle/Doctrine/ODM/PHPCR/EventListener/DefaultParentListener.php
  src/Bundle/Doctrine/ODM/PHPCR/EventListener/NameFilterListener.php
  src/Bundle/Doctrine/ODM/PHPCR/EventListener/NameResolverListener.php
  src/Bundle/Doctrine/ODM/PHPCR/Form/Builder/DefaultFormBuilder.php
  src/Bundle/EventListener/ODMMappedSuperClassSubscriber.php
  src/Bundle/EventListener/ODMRepositoryClassSubscriber.php
  src/Bundle/EventListener/ODMTranslatableListener.php
  src/Bundle/EventListener/ORMTranslatableListener.php
  src/Bundle/ExpressionLanguage/ExpressionLanguage.php
  src/Bundle/Storage/SessionStorage.php
  src/Bundle/SyliusResourceBundle.php
Labels: Enhancement, DX

#341 Dropping usage of Request->get
  src/Bundle/Controller/ParametersParser.php
  src/Bundle/Controller/RequestConfiguration.php
  src/Bundle/Provider/RequestParameterProvider.php
  src/Bundle/Tests/Provider/RequestParameterProviderTest.php
  src/Bundle/spec/Controller/RequestConfigurationSpec.php
Labels: Bug

#487 Make CsrfTokenManager public
  .github/workflows/build.yml
  src/Bundle/DependencyInjection/Compiler/CsrfTokenManagerPass.php
  src/Bundle/SyliusResourceBundle.php
  src/Bundle/test/src/Tests/Controller/ScienceBookUiTest.php
  src/Bundle/test/src/Tests/DataFixtures/ORM/single_science_book.yml
  src/Bundle/test/templates/ScienceBook/index.html.twig
Labels: Bug

#488 Return 422 status code when the form fails
  src/Bundle/Controller/ControllerTrait.php
  src/Bundle/Controller/ResourceController.php
  src/Bundle/test/config/services.yaml
  src/Bundle/test/config/sylius/resources.yaml
  src/Bundle/test/config/validator/validation.yaml
  src/Bundle/test/src/Form/Type/AuthorType.php
  src/Bundle/test/src/Form/Type/ScienceBookType.php
  src/Bundle/test/src/Tests/Controller/ScienceBookUiTest.php
Labels: Bug

#489 Fix can apply a transition on workflow with a graph
  src/Bundle/Controller/Workflow.php
  src/Bundle/spec/Controller/WorkflowSpec.php
Labels: Bug

#492 [Maintenance] Out-of-date phpstan/phpdoc-parser conflict removed, docker static analysis memory limit increased
  CONFLICTS.md
  composer.json
Labels: Maintenance

#495 Inform about potential BC break after response code change
  UPGRADE.md
Labels: Maintenance
