Repository Sylius/SyliusResourceBundle, pull requests merged in 2022-01, with the labels that each got.

#344 Remove travis build status from README
  README.md
  src/Component/README.md
Labels: Maintenance

#287 Manage event response in show and index action to be able to redirect
  src/Bundle/Controller/ResourceController.php
  src/Bundle/spec/Controller/ResourceControllerSpec.php
Labels: Feature

#334 Sylius route with attributes
  phpstan.neon
  psalm.xml
  src/Bundle/DependencyInjection/Configuration.php
  src/Bundle/DependencyInjection/SyliusResourceExtension.php
  src/Bundle/Doctrine/ORM/EntityRepository.php
  src/Bundle/Doctrine/ORM/ResourceRepositoryTrait.php
  src/Bundle/Resources/config/services/routing.xml
  src/Bundle/Routing/CrudRoutesAttributesLoader.php
  src/Bundle/Routing/RouteAttributesFactory.php
  src/Bundle/Routing/RouteAttributesFactoryInterface.php
  src/Bundle/Routing/RoutesAttributesLoader.php
  src/Bundle/Tests/Configuration/ConfigurationTest.php
  src/Bundle/Tests/DependencyInjection/SyliusResourceExtensionTest.php
  src/Bundle/Tests/Routing/CrudRoutesAttributesLoaderTest.php
  src/Bundle/Tests/Routing/RoutesAttributesLoaderTest.php
  src/Bundle/spec/Routing/CrudRoutesAttributesLoaderSpec.php
  src/Bundle/spec/Routing/RouteAttributesFactorySpec.php
  src/Bundle/spec/Routing/RoutesAttributesLoaderSpec.php
  src/Bundle/test/config/routes/test_with_attributes/sylius_resource.yaml
  src/Bundle/test/src/Entity/CrudRoutes/BookWithAlias.php
  src/Bundle/test/src/Entity/CrudRoutes/BookWithCriteria.php
  src/Bundle/test/src/Entity/CrudRoutes/BookWithExcept.php
  src/Bundle/test/src/Entity/CrudRoutes/BookWithGrid.php
  src/Bundle/test/src/Entity/CrudRoutes/BookWithOnly.php
  src/Bundle/test/src/Entity/CrudRoutes/BookWithPermission.php
  src/Bundle/test/src/Entity/CrudRoutes/BookWithRedirect.php
  src/Bundle/test/src/Entity/CrudRoutes/BookWithSection.php
  src/Bundle/test/src/Entity/CrudRoutes/BookWithTemplate.php
  src/Bundle/test/src/Entity/CrudRoutes/BookWithVars.php
  src/Bundle/test/src/Entity/Route/ShowBook.php
  src/Bundle/test/src/Entity/Route/ShowBookWithCriteria.php
  src/Bundle/test/src/Entity/Route/ShowBookWithHost.php
  src/Bundle/test/src/Entity/Route/ShowBookWithMethods.php
  src/Bundle/test/src/Entity/Route/ShowBookWithOptions.php
  src/Bundle/test/src/Entity/Route/ShowBookWithPriority.php
  src/Bundle/test/src/Entity/Route/ShowBookWithRepository.php
  src/Bundle/test/src/Entity/Route/ShowBookWithRequirements.php
  src/Bundle/test/src/Entity/Route/ShowBookWithSchemes.php
  src/Bundle/test/src/Entity/Route/ShowBookWithSerializationGroups.php
  src/Bundle/test/src/Entity/Route/ShowBookWithSerializationVersion.php
  src/Bundle/test/src/Entity/Route/ShowBookWithTemplate.php
  src/Bundle/test/src/Entity/Route/ShowBookWithVars.php
  src/Bundle/test/src/Repository/ComicBookRepository.php
  src/Component/Annotation/SyliusCrudRoutes.php
  src/Component/Annotation/SyliusRoute.php
  src/Component/Reflection/ClassReflection.php
  src/Component/Tests/Dummy/DummyClassOne.php
  src/Component/Tests/Dummy/DummyClassTwo.php
  src/Component/Tests/Dummy/TraitPass.php
  src/Component/Tests/Reflection/ClassReflectionTest.php
Labels: Feature

#354 Reactivate checking coding standard
  composer.json
Labels: Maintenance

#353 Require symfony/routing and symfony/http-foundation 4.4 and 5.4
  composer.json
Labels: Bug, Maintenance

#355 Tests for index and show in UI
  src/Bundle/test/config/doctrine/ScienceBook.orm.yml
  src/Bundle/test/config/packages/test/fos_rest.yaml
  src/Bundle/test/config/packages/test/twig.yaml
  src/Bundle/test/config/routes.yaml
  src/Bundle/test/config/sylius/resources.yaml
  src/Bundle/test/src/Entity/ScienceBook.php
  src/Bundle/test/src/Tests/Controller/ScienceBookUiTest.php
  src/Bundle/test/src/Tests/DataFixtures/ORM/science_books.yml
  src/Bundle/test/templates/ScienceBook/index.html.twig
  src/Bundle/test/templates/ScienceBook/show.html.twig
Labels: Enhancement, DX

#358 Fix docs for crud routes with attributes
  docs/routing.md
Labels: Bug

#359 Fix type of serialization groups
  src/Component/Annotation/SyliusRoute.php
Labels: Bug

#360 Allow to run GitHub actions manually
  .github/workflows/build.yml
Labels: Enhancement, DX
