Repository Sylius/SyliusResourceBundle, pull requests merged in 2022-04, with the labels that each got.

#403 Add form attribute on SyliusCrudRoute
  src/Bundle/Routing/RouteAttributesFactory.php
  src/Bundle/Tests/Routing/RoutesAttributesLoaderTest.php
  src/Bundle/spec/Routing/RouteAttributesFactorySpec.php
  src/Bundle/spec/Routing/RoutesAttributesLoaderSpec.php
  src/Bundle/test/config/doctrine/User.orm.yml
  src/Bundle/test/src/Entity/Route/RegisterUserWithForm.php
  src/Bundle/test/src/Entity/User.php
  src/Bundle/test/src/Form/Type/RegisterType.php
  src/Component/Annotation/SyliusRoute.php
Labels: Feature

#406 Allow to run GitHub actions manually + fix build on 1.8
  .github/workflows/build.yml
  src/Bundle/test/config/services.yaml
Labels: Bug, Maintenance

#416 Revert "Bump Pagerfanta from 2.x to 3.x"
  composer.json
  phpstan.neon
  src/Bundle/Tests/DependencyInjection/Compiler/PagerfantaBridgePassTest.php
  src/Bundle/spec/Controller/ResourcesCollectionProviderSpec.php
  src/Component/composer.json
Labels: Bug

#424 Run lint container instead of smoke test for twig
  .github/workflows/build.yml
  src/Bundle/test/config/bundles.php
Labels: Enhancement, Maintenance

#380 Fix session deprecation
  src/Bundle/Controller/FlashHelper.php
  src/Bundle/DependencyInjection/Compiler/SessionPass.php
  src/Bundle/Resources/config/services/controller.xml
  src/Bundle/Resources/config/services/storage.xml
  src/Bundle/Storage/SessionStorage.php
  src/Bundle/SyliusResourceBundle.php
  src/Bundle/Tests/DependencyInjection/Compiler/SessionPassTest.php
  src/Bundle/spec/Controller/FlashHelperSpec.php
  src/Bundle/spec/Storage/SessionStorageSpec.php
Labels: Enhancement, Maintenance

#379 Fix setDeprecated deprecation
  src/Bundle/DependencyInjection/Compiler/PagerfantaBridgePass.php
Labels: Enhancement, Maintenance

#398 [Symfony 6] Fix Parameters return type
  src/Bundle/Controller/Parameters.php
Labels: Bug

#401 [Symfony 6] Use storage factory id option on test app
  .github/workflows/build.yml
  src/Bundle/test/config/packages/framework.yaml
Labels: Enhancement

#430 Drop Symfony 4 support
  .github/workflows/build.yml
  composer.json
  src/Component/composer.json
Labels: Maintenance

#407 [1.8] Correct branch alias to 1.8-dev
  composer.json
Labels: Bug, Maintenance

#409 Document supported branches
  README.md
Labels: Maintenance

#402 [Symfony 6] Fix http foundation request handler typehints
  src/Bundle/Form/Extension/HttpFoundation/HttpFoundationRequestHandler.php
Labels: Enhancement

#408 [1.10] Correct branch alias to 1.10-dev
  composer.json
Labels: Maintenance

#431 Simplify Kernel on test app
  src/Bundle/test/src/Kernel.php
Labels: Enhancement, DX

#433 Remove session pass
  src/Bundle/DependencyInjection/Compiler/SessionPass.php
  src/Bundle/SyliusResourceBundle.php
  src/Bundle/Tests/DependencyInjection/Compiler/SessionPassTest.php
Labels: Maintenance

#411 [Symfony 6] Bump Psalm version from 4.7 to 4.22
  .github/workflows/build.yml
  composer.json
  psalm.xml
  src/Bundle/DependencyInjection/Compiler/Helper/TargetEntitiesResolver.php
  src/Bundle/Routing/RouteAttributesFactoryInterface.php
  src/Component/Reflection/ClassReflection.php
Labels: Maintenance

#412 [Symfony 6] Fix bootstrap on test app
  src/Bundle/test/config/bootstrap.php
Labels: Maintenance

#426 Add missing options on sylius route attribute
  docs/show_resource.md
  docs/update_resource.md
  src/Bundle/Routing/RouteAttributesFactory.php
  src/Bundle/Tests/Routing/RoutesAttributesLoaderTest.php
  src/Bundle/spec/Routing/RoutesAttributesLoaderSpec.php
  src/Bundle/test/src/Entity/Route/PublishBook.php
  src/Bundle/test/src/Entity/Route/RegisterUserWithFormOptions.php
  src/Bundle/test/src/Entity/Route/ShowBookWithCsrfProtection.php
  src/Bundle/test/src/Entity/Route/ShowBookWithGrid.php
  src/Bundle/test/src/Entity/Route/ShowBookWithPermission.php
  src/Bundle/test/src/Entity/Route/ShowBookWithSection.php
  src/Bundle/test/src/Entity/Route/UpdateBookWithCustomEventName.php
  src/Bundle/test/src/Entity/Route/UpdateBookWithRedirect.php
  src/Bundle/test/src/Entity/Route/UpdateBookWithRedirectOptions.php
  src/Bundle/test/src/Entity/Route/UpdateBookWithReturnContent.php
  src/Component/Annotation/SyliusRoute.php
Labels: Feature, DX

#434 [Maintenance] Bump EasyCodingStandard dependency
  composer.json
  src/Bundle/Controller/ResourceController.php
  src/Bundle/Tests/Resource/ResourceServicesTest.php
Labels: Maintenance

#435 [Maintenance] Removal of Sf4.4 BC layer leftovers
  .github/workflows/build.yml
  src/Bundle/test/config/packages/framework.yaml
Labels: Maintenance

#413 [Symfony 6] Fix setting deprecations on pagerfanta bridge pass
  phpstan.neon
  src/Bundle/DependencyInjection/Compiler/PagerfantaBridgePass.php
  src/Component/Reflection/ClassReflection.php
Labels: Maintenance

#437 Remove is master request usage
  psalm.xml
  src/Bundle/Storage/CookieStorage.php
Labels: Maintenance

#440 Fix some other getting container deprecations
  src/Bundle/Tests/Resource/ResourceServicesTest.php
  src/Bundle/Tests/Routing/RoutesAttributesLoaderTest.php
Labels: Maintenance

#439 Fix Phpspec for symfony 6
  src/Bundle/spec/Controller/ParametersParserSpec.php
  src/Bundle/spec/Controller/ResourceControllerSpec.php
  src/Bundle/spec/Doctrine/ORM/Form/Builder/DefaultFormBuilderSpec.php
  src/Bundle/spec/Form/EventSubscriber/AddCodeFormSubscriberSpec.php
Labels: Bug

#444 [Symfony 6] Third solution to fix resource controllers
  src/Bundle/DependencyInjection/Compiler/TwigPass.php
  src/Bundle/Doctrine/ORM/ContainerRepositoryFactory.php
  src/Bundle/SyliusResourceBundle.php
Labels: Bug
