Repository Sylius/SyliusResourceBundle, pull requests merged in 2023-09, with the labels that each got.

#616 Allow doctrine/collections ^2.0
  .github/workflows/build.yml
  composer.json
  src/Bundle/Form/DataTransformer/RecursiveTransformer.php
  src/Bundle/Form/DataTransformer/ResourceToIdentifierTransformer.php
  src/Component/composer.json
Labels: Maintenance

#742 Define simple vars on your operations
  docs/configure_your_operations.md
  docs/configure_your_resource.md
  src/Bundle/Resources/config/services/metadata.xml
  src/Component/Metadata/BulkDelete.php
  src/Component/Metadata/BulkUpdate.php
  src/Component/Metadata/Create.php
  src/Component/Metadata/Delete.php
  src/Component/Metadata/HttpOperation.php
  src/Component/Metadata/Index.php
  src/Component/Metadata/Resource.php
  src/Component/Metadata/Resource/Factory/VarsResourceMetadataCollectionFactory.php
  src/Component/Metadata/Show.php
  src/Component/Metadata/Update.php
  src/Component/Symfony/Routing/Factory/OperationRouteFactory.php
  src/Component/spec/Metadata/Resource/Factory/VarsResourceMetadataCollectionFactorySpec.php
  src/Component/spec/Metadata/ResourceSpec.php
  src/Component/spec/Symfony/Routing/Factory/OperationRouteFactorySpec.php
  tests/Bundle/Command/DebugResourceCommandTest.php
Labels: Feature

#732 Remove unused template
  src/Bundle/test/templates/subscription/grid/bulk_action/accept.html.twig
Labels: Enhancement, DX

#729 [doc] Add missing new line to configure_your_operations.md example
  docs/configure_your_operations.md
Labels: Bug, DX

#740 [Fix] Update delete path name to avoid route conflicts
  src/Component/Metadata/Api/ApiOperationInterface.php
  src/Component/Metadata/Api/Delete.php
  src/Component/Metadata/Api/Get.php
  src/Component/Metadata/Api/GetCollection.php
  src/Component/Metadata/Api/Patch.php
  src/Component/Metadata/Api/Post.php
  src/Component/Metadata/Api/Put.php
  src/Component/Symfony/Routing/Factory/DeleteOperationRoutePathFactory.php
  src/Component/spec/Symfony/Routing/Factory/DeleteOperationRoutePathFactorySpec.php
  tests/Application/src/Subscription/Entity/Subscription.php
  tests/Application/src/Tests/Controller/BoardGameUiTest.php
  tests/Application/src/Tests/Controller/SubscriptionUiTest.php
Labels: Bug

#745 Improve testing debug resource command
  tests/Bundle/Command/DebugResourceCommandTest.php
Labels: Enhancement, DX
