Repository Sylius/SyliusResourceBundle, pull requests merged in 2024-10, with the labels that each got.

#949 [Composer] Bump sylius/grid-bundle dev dependency
  .github/workflows/build.yml
  composer.json
Labels: Maintenance, dependencies

#873 Move winzou state machine on optional requirements
  .github/workflows/build.yml
  UPGRADE.md
  composer.json
Labels: Maintenance, dependencies

#951 [Composer] Add GridBundle 1.13 beta in dev dependencies for SF7 builds
  composer.json
Labels: Bug, Maintenance, dependencies

#957 Deprecate VariantWithNoOptionsValuesException
  UPGRADE.md
  psalm.xml
  src/Component/legacy/src/Exception/VariantWithNoOptionsValuesException.php
  src/Component/src/Exception/VariantWithNoOptionsValuesException.php
Labels: Maintenance
