Repository Sylius/SyliusResourceBundle, pull requests merged in 2024-09, with the labels that each got.

#863 Adding support for Symfony 7
  .github/workflows/build.yml
  CONFLICTS.md
  Dockerfile
  composer.json
  phpstan.neon
  psalm.xml
  src/Bundle/Controller/ContainerAwareTrait.php
  src/Bundle/Controller/Parameters.php
  src/Bundle/Controller/ResourceController.php
  src/Bundle/DependencyInjection/Compiler/DoctrineTargetEntitiesResolverPass.php
  src/Bundle/Form/DataTransformer/ResourceToIdentifierTransformer.php
  src/Bundle/Resources/config/services/integrations/translation.xml
  src/Bundle/Resources/config/services/routing.xml
  src/Bundle/Routing/ResourceLoader.php
  src/Bundle/spec/Controller/RedirectHandlerSpec.php
  src/Bundle/spec/Controller/RequestConfigurationFactorySpec.php
  src/Bundle/spec/Controller/RequestConfigurationSpec.php
  src/Bundle/spec/Controller/ResourceControllerSpec.php
  src/Bundle/spec/Controller/ResourcesCollectionProviderSpec.php
  src/Bundle/spec/Grid/Controller/ResourcesResolverSpec.php
  src/Component/composer.json
  src/Component/legacy/tests/Symfony/EventListener/AddFormatListenerTest.php
  src/Component/spec/Symfony/Request/RepositoryArgumentResolverSpec.php
  src/Component/spec/Symfony/Request/State/ProviderSpec.php
  tests/Application/config/bundles.php
  tests/Application/config/packages/security.yaml
  tests/Application/config/packages/test_without_fosrest/framework.yaml
  tests/Application/config/packages/test_without_fosrest/grids.yaml
  tests/Application/config/packages/test_without_fosrest/sylius_grid.yaml
  tests/Application/config/packages/test_without_fosrest/winzou_state_machine.yaml
  tests/Application/config/packages/test_without_hateoas/fos_rest.yaml
  tests/Application/config/packages/test_without_hateoas/framework.yaml
  tests/Application/config/packages/test_without_hateoas/grids.yaml
  tests/Application/config/packages/test_without_hateoas/jms_serializer.yaml
  tests/Application/config/packages/test_without_hateoas/sylius_grid.yaml
  tests/Application/config/packages/test_without_hateoas/twig.yaml
  tests/Application/config/packages/test_without_hateoas/winzou_state_machine.yaml
  tests/Application/config/services.yaml
  tests/Application/config/sylius/resources.yaml
  tests/Application/src/Entity/Zone/Zone.php
  tests/Application/src/Entity/Zone/ZoneInterface.php
  tests/Application/src/Entity/Zone/ZoneMember.php
  tests/Application/src/Entity/Zone/ZoneMemberInterface.php
  tests/Application/src/Kernel.php
  tests/Application/src/Subscription/Entity/Subscription.php
  tests/Application/src/Tests/Controller/BookApiTest.php
  tests/Application/src/Tests/Controller/ComicBookApiTest.php
Labels: Maintenance

#918 Fix grid limits on request grid provider
  composer.json
  src/Component/spec/Grid/State/RequestGridProviderSpec.php
  src/Component/src/Grid/State/RequestGridProvider.php
  tests/Application/src/Subscription/Grid/SubscriptionGrid.php
  tests/Application/src/Tests/Controller/SubscriptionUiTest.php
  tests/Application/src/Tests/DataFixtures/ORM/subscriptions.yml
  tests/Application/src/Tests/Responses/subscriptions/index_response.json
  tests/Application/src/Tests/Responses/subscriptions/index_response.xml
Labels: Bug

#914 [Docs] Disable processing data
  docs/processors.md
Labels: Documentation

#925 [Docs] Resource validation
  docs/configure_your_operations.md
  docs/index.md
  docs/validation.md
Labels: Documentation

#926 [Composer] Allow GridBundle ^v1.13@alpha
  composer.json
  src/Component/composer.json
Labels: Maintenance, dependencies

#935 Fix getting translation repository
  src/Bundle/DependencyInjection/Compiler/DoctrineTargetEntitiesResolverPass.php
  tests/Bundle/DependencyInjection/Compiler/DoctrineTargetEntitiesResolverPassTest.php
Labels: Bug

#941 Fix Doctrine dependency on state processors
  src/Bundle/Resources/config/services/integrations/doctrine.xml
  src/Bundle/Resources/config/services/state.xml
Labels: Bug

#928 [phpspec-2-phpunit] migration of tests (Doctrine)
  src/Component/spec/Doctrine/Common/Metadata/Resource/Factory/DoctrineResourceMetadataCollectionFactorySpec.php
  src/Component/spec/Doctrine/Common/State/PersistProcessorSpec.php
  src/Component/spec/Doctrine/Common/State/RemoveProcessorSpec.php
  src/Component/spec/Doctrine/Persistence/Exception/ResourceExistsExceptionSpec.php
  src/Component/spec/Doctrine/Persistence/InMemoryRepositorySpec.php
  src/Component/tests/Doctrine/Common/Metadata/Resource/Factory/DoctrineResourceMetadataCollectionFactoryTest.php
  src/Component/tests/Doctrine/Common/State/PersistProcessorTest.php
  src/Component/tests/Doctrine/Common/State/RemoveProcessorTest.php
  src/Component/tests/Doctrine/Persistence/Exception/ResourceExistsExceptionTest.php
  src/Component/tests/Doctrine/Persistence/InMemoryRepositoryTest.php
Labels: Maintenance

#930 [phpspec-2-phpunit] migration of tests (Generator)
  src/Component/legacy/spec/Generator/RandomnessGeneratorSpec.php
  src/Component/spec/Generator/RandomnessGeneratorSpec.php
  src/Component/tests/Generator/RandomnessGeneratorTest.php
Labels: Maintenance

#931 [phpspec-2-phpunit] migration of tests (Grid)
  src/Component/spec/Grid/State/RequestGridProviderSpec.php
  src/Component/tests/Grid/State/RequestGridProviderTest.php
Labels: Maintenance

#933 [phpspec-2-phpunit] migration of tests (Metadata)
  src/Component/spec/Metadata/ApplyStateMachineTransitionSpec.php
  src/Component/spec/Metadata/BulkDeleteSpec.php
  src/Component/spec/Metadata/CreateSpec.php
  src/Component/spec/Metadata/DeleteSpec.php
  src/Component/spec/Metadata/HttpOperationSpec.php
  src/Component/spec/Metadata/IndexSpec.php
  src/Component/spec/Metadata/MetadataSpec.php
  src/Component/spec/Metadata/Operation/HttpOperationInitiatorSpec.php
  src/Component/spec/Metadata/OperationsSpec.php
  src/Component/spec/Metadata/RegistrySpec.php
  src/Component/spec/Metadata/Resource/Factory/AttributesResourceMetadataCollectionFactorySpec.php
  src/Component/spec/Metadata/Resource/Factory/CachedResourceMetadataCollectionFactorySpec.php
  src/Component/spec/Metadata/Resource/Factory/FactoryResourceMetadataCollectionFactorySpec.php
  src/Component/spec/Metadata/Resource/Factory/TemplatesDirResourceMetadataCollectionFactorySpec.php
  src/Component/spec/Metadata/Resource/ResourceMetadataCollectionSpec.php
  src/Component/spec/Metadata/ResourceMetadataSpec.php
  src/Component/spec/Metadata/ShowSpec.php
  src/Component/spec/Metadata/UpdateSpec.php
  src/Component/tests/Metadata/ApplyStateMachineTransitionTest.php
  src/Component/tests/Metadata/BulkDeleteTest.php
  src/Component/tests/Metadata/CreateTest.php
  src/Component/tests/Metadata/DeleteTest.php
  src/Component/tests/Metadata/HttpOperationTest.php
  src/Component/tests/Metadata/IndexTest.php
  src/Component/tests/Metadata/MetadataTest.php
  src/Component/tests/Metadata/Operation/HttpOperationInitiatorTest.php
  src/Component/tests/Metadata/OperationsTest.php
  src/Component/tests/Metadata/RegistryTest.php
  src/Component/tests/Metadata/Resource/Factory/AttributesResourceMetadataCollectionFactoryTest.php
  src/Component/tests/Metadata/Resource/Factory/CachedResourceMetadataCollectionFactoryTest.php
  src/Component/tests/Metadata/Resource/Factory/EventShortNameResourceMetadataCollectionFactoryTest.php
  src/Component/tests/Metadata/Resource/Factory/FactoryResourceMetadataCollectionFactoryTest.php
  src/Component/tests/Metadata/Resource/Factory/ProviderResourceMetadataCollectionFactoryTest.php
  src/Component/tests/Metadata/Resource/Factory/RedirectResourceMetadataCollectionFactoryTest.php
  src/Component/tests/Metadata/Resource/Factory/StateMachineResourceMetadataCollectionFactoryTest.php
  src/Component/tests/Metadata/Resource/Factory/TemplatesDirResourceMetadataCollectionFactoryTest.php
  src/Component/tests/Metadata/Resource/Factory/VarsResourceMetadataCollectionFactoryTest.php
  src/Component/tests/Metadata/Resource/ResourceMetadataCollectionTest.php
  src/Component/tests/Metadata/ResourceMetadataTest.php
  src/Component/tests/Metadata/ShowTest.php
  src/Component/tests/Metadata/UpdateTest.php
Labels: Maintenance

#945 Restrict Doctrine orm package version
  composer.json
  src/Bundle/Doctrine/ORM/Form/Builder/DefaultFormBuilder.php
  src/Bundle/EventListener/ORMMappedSuperClassSubscriber.php
  src/Bundle/EventListener/ORMTranslatableListener.php
  src/Bundle/spec/Doctrine/ORM/Form/Builder/DefaultFormBuilderSpec.php
  src/Component/composer.json
  src/Component/src/Doctrine/Common/State/PersistProcessor.php
  src/Component/tests/Doctrine/Common/State/PersistProcessorTest.php
Labels: Maintenance, dependencies

#861 [Maintenance] Deprecate unused configuration nodes
  docs/reference.md
  src/Bundle/DependencyInjection/Configuration.php
Labels: Maintenance
