Repository Sylius/SyliusResourceBundle, pull requests merged in 2025-01, with the labels that each got.

#968 Add support for Doctrine ORM 3
  .github/workflows/build.yml
  Dockerfile
  composer.json
  phpstan.neon
  psalm.xml
  src/Bundle/Doctrine/ORM/ContainerRepositoryFactory.php
  src/Bundle/Doctrine/ORM/ResourceRepositoryTrait.php
  src/Bundle/EventListener/ORMMappedSuperClassSubscriber.php
  src/Bundle/EventListener/ORMTranslatableListener.php
  src/Component/composer.json
  tests/Application/src/Entity/GedmoBaseExample.php
  tests/Application/src/Entity/GedmoExtendedExample.php
Labels: Maintenance, dependencies

#969 [DX][Internal] Start using Foundry
  composer.json
  tests/Application/config/bundles.php
  tests/Application/src/Foundry/Factory/BookFactory.php
  tests/Application/src/Foundry/Factory/BookTranslationFactory.php
  tests/Application/src/Foundry/Story/DefaultBooksStory.php
  tests/Application/src/Foundry/Story/MoreBooksStory.php
  tests/Application/src/Tests/Controller/BookApiTest.php
Labels: DX

#970 [DX][Internal] use Foundry for comic books
  Dockerfile
  tests/Application/src/Foundry/Factory/AuthorFactory.php
  tests/Application/src/Foundry/Factory/ComicBookFactory.php
  tests/Application/src/Foundry/Story/DefaultComicBooksStory.php
  tests/Application/src/Foundry/Story/MoreBooksStory.php
  tests/Application/src/Tests/Controller/ComicBookApiTest.php
  tests/Application/src/Tests/DataFixtures/ORM/comic_books.yml
Labels: DX

#973 Fix Delete handling exception previous argument type
  src/Component/src/Exception/DeleteHandlingException.php
Labels: Enhancement, Bug

#971 [DX][Internal] Do not use Alice anymore
  tests/Application/src/BoardGameBlog/Infrastructure/Foundry/Factory/BoardGameFactory.php
  tests/Application/src/Foundry/Factory/BlogPostFactory.php
  tests/Application/src/Foundry/Factory/PullRequestFactory.php
  tests/Application/src/Foundry/Factory/ScienceBookFactory.php
  tests/Application/src/Subscription/Foundry/Factory/SubscriptionFactory.php
  tests/Application/src/Subscription/Foundry/Story/DefaultSubscriptionsStory.php
  tests/Application/src/Tests/Controller/BlogPostApiTest.php
  tests/Application/src/Tests/Controller/BoardGameUiTest.php
  tests/Application/src/Tests/Controller/BookApiTest.php
  tests/Application/src/Tests/Controller/ComicBookApiTest.php
  tests/Application/src/Tests/Controller/PullRequestApiTest.php
  tests/Application/src/Tests/Controller/ScienceBookUiTest.php
  tests/Application/src/Tests/Controller/SubscriptionJsonApiTest.php
  tests/Application/src/Tests/Controller/SubscriptionUiTest.php
  tests/Application/src/Tests/Controller/SubscriptionXmlApiTest.php
  tests/Application/src/Tests/DataFixtures/ORM/blog-posts.yml
  tests/Application/src/Tests/DataFixtures/ORM/board_games.yml
  tests/Application/src/Tests/DataFixtures/ORM/books.yml
  tests/Application/src/Tests/DataFixtures/ORM/more_books.yml
  tests/Application/src/Tests/DataFixtures/ORM/pull-requests.yml
  tests/Application/src/Tests/DataFixtures/ORM/science_books.yml
  tests/Application/src/Tests/DataFixtures/ORM/single_board_game.yml
  tests/Application/src/Tests/DataFixtures/ORM/single_science_book.yml
  tests/Application/src/Tests/DataFixtures/ORM/single_subscription.yml
  tests/Application/src/Tests/DataFixtures/ORM/subscriptions.yml
  tests/Application/src/Tests/Validator/TranslatableValidatorTest.php
Labels: DX

#963 [Doc] Documentation migration to SyliusStack using gitbook
  .gitattributes
  README.md
  docs/configuration.md
  docs/configure_your_operations.md
  docs/configure_your_resource.md
  docs/create_new_resource.md
  docs/create_resource.md
  docs/delete_resource.md
  docs/forms.md
  docs/index.md
  docs/index_resources.md
  docs/installation.md
  docs/processors.md
  docs/providers.md
  docs/redirect.md
  docs/reference.md
  docs/resource_factories.md
  docs/responders.md
  docs/routing.md
  docs/services.md
  docs/show_resource.md
  docs/state_machine.md
  docs/update_resource.md
  docs/validation.md
Labels: Documentation

#975 Add missing package and version attributes in deprecated element
  src/Bundle/Resources/config/services/integrations/doctrine/mongodb-odm.xml
Labels: Bug, Maintenance
